#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H
// Auto-generated by pipeline/dump_deploy_constants.py.
// Deployment constants for the int8 CNN (beat_cnn_rr_int8.tflite).

#define ECG_FS     360
#define WIN_PRE    90   // samples before R (0.25 s)
#define WIN_POST   162  // samples after R (0.45 s)
#define WIN_LEN    252
#define N_CLASSES  5

// Per-beat: z-normalize the raw window (subtract its mean, divide by
// its std) BEFORE quantizing with BEAT_IN_SCALE/ZP.
#define BEAT_IN_SCALE  0.045357101f
#define BEAT_IN_ZP     -25

// RR scalars: std_val[k] = (raw[k]-RR_MEAN[k])/RR_STD[k], then quantize.
//   index 0 = prev_RR (seconds), 1 = RR_ratio (prev_RR / local-avg RR)
static const float RR_MEAN[2] = { 0.77852273f, 1.0000019f };
static const float RR_STD[2]  = { 0.49549153f, 0.15599644f };
#define RR_IN_SCALE    0.028470248f
#define RR_IN_ZP       -28

// int8 quantize:   q = (int8) round(x / scale + zero_point), clip [-128,127]
// int8 dequantize: y = (q - zero_point) * scale
#define OUT_SCALE      0.00390625f
#define OUT_ZP         -128

static const char *CLASS_NAMES[5] = { "N", "S", "V", "F", "Q" };

#endif  // MODEL_CONFIG_H
