"""
dump_deploy_constants.py — Stage 2.3 prep: emit the numbers the firmware needs
to feed the int8 CNN on the F411.

The int8 model can't be used on-device without three sets of constants that
live only in the training/quantization step:
  1. RR standardization (mean/std of prev_RR and RR_ratio, from DS1 train) —
     applied to the RR scalars BEFORE quantization, same as training.
  2. int8 INPUT quantization (scale, zero-point) for the beat window and the RR
     vector — to turn float preprocessed values into int8 the model expects.
  3. int8 OUTPUT quantization (scale, zero-point) — to turn the int8 logits
     back into class scores.

Writes models/model_config.h (a small C header) plus prints everything.

Run from the repo root:
    python -m pipeline.dump_deploy_constants
"""

import os
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

import argparse
import numpy as np
import tensorflow as tf

from .data_loader import AAMI_CLASSES, DS1_TRAIN, FS
from .train_cnn_rr import build_dataset, normalize_rr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tflite", default="models/beat_cnn_rr_int8.tflite")
    ap.add_argument("--pre-s", type=float, default=0.25)
    ap.add_argument("--post-s", type=float, default=0.45)
    ap.add_argument("--pn-dir", default="mitdb")
    ap.add_argument("--out", default="models/model_config.h")
    args = ap.parse_args()

    pre, post = int(args.pre_s * FS), int(args.post_s * FS)
    win = pre + post

    # --- RR standardization stats from DS1 (same as training/quantization) ---
    print("Rebuilding DS1 for RR standardization stats ...")
    _, Rtr, _ = build_dataset(DS1_TRAIN, pre, post, args.pn_dir)
    _, (rr_mean, rr_std) = normalize_rr(Rtr)   # (list, (mean,std)); index 0=prev_RR, 1=ratio

    # --- int8 quant params from the .tflite ---
    interp = tf.lite.Interpreter(model_path=args.tflite)
    interp.allocate_tensors()
    ins = interp.get_input_details()
    out = interp.get_output_details()[0]
    beat_d = max(ins, key=lambda d: int(np.prod(d["shape"])))   # 252-wide window
    rr_d = min(ins, key=lambda d: int(np.prod(d["shape"])))     # 2 scalars

    bscale, bzp = beat_d["quantization"]
    rscale, rzp = rr_d["quantization"]
    oscale, ozp = out["quantization"]

    print("\n--- input tensors (order matters for the runtime) ---")
    for i, d in enumerate(ins):
        tag = "BEAT" if d is beat_d else "RR"
        print(f"  input[{i}] {tag:4s} name={d['name']:28s} shape={list(d['shape'])} "
              f"scale={d['quantization'][0]:.8g} zp={d['quantization'][1]}")
    print(f"  output    name={out['name']:28s} shape={list(out['shape'])} "
          f"scale={oscale:.8g} zp={ozp}")
    print(f"\nRR_MEAN = {rr_mean}")
    print(f"RR_STD  = {rr_std}")

    # --- emit C header ---
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write("#ifndef MODEL_CONFIG_H\n#define MODEL_CONFIG_H\n")
        f.write("// Auto-generated by pipeline/dump_deploy_constants.py.\n")
        f.write("// Deployment constants for the int8 CNN (beat_cnn_rr_int8.tflite).\n\n")
        f.write(f"#define ECG_FS     {FS}\n")
        f.write(f"#define WIN_PRE    {pre}   // samples before R ({args.pre_s:.2f} s)\n")
        f.write(f"#define WIN_POST   {post}  // samples after R ({args.post_s:.2f} s)\n")
        f.write(f"#define WIN_LEN    {win}\n")
        f.write(f"#define N_CLASSES  {len(AAMI_CLASSES)}\n\n")
        f.write("// Per-beat: z-normalize the raw window (subtract its mean, divide by\n")
        f.write("// its std) BEFORE quantizing with BEAT_IN_SCALE/ZP.\n")
        f.write(f"#define BEAT_IN_SCALE  {bscale:.8g}f\n")
        f.write(f"#define BEAT_IN_ZP     {bzp}\n\n")
        f.write("// RR scalars: std_val[k] = (raw[k]-RR_MEAN[k])/RR_STD[k], then quantize.\n")
        f.write("//   index 0 = prev_RR (seconds), 1 = RR_ratio (prev_RR / local-avg RR)\n")
        f.write(f"static const float RR_MEAN[2] = {{ {rr_mean[0]:.8g}f, {rr_mean[1]:.8g}f }};\n")
        f.write(f"static const float RR_STD[2]  = {{ {rr_std[0]:.8g}f, {rr_std[1]:.8g}f }};\n")
        f.write(f"#define RR_IN_SCALE    {rscale:.8g}f\n")
        f.write(f"#define RR_IN_ZP       {rzp}\n\n")
        f.write("// int8 quantize:   q = (int8) round(x / scale + zero_point), clip [-128,127]\n")
        f.write("// int8 dequantize: y = (q - zero_point) * scale\n")
        f.write(f"#define OUT_SCALE      {oscale:.8g}f\n")
        f.write(f"#define OUT_ZP         {ozp}\n\n")
        names = ", ".join(f'"{c}"' for c in AAMI_CLASSES)
        f.write(f"static const char *CLASS_NAMES[{len(AAMI_CLASSES)}] = {{ {names} }};\n\n")
        f.write("#endif  // MODEL_CONFIG_H\n")
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
