"""
export_to_c.py — turn a slice of a MIT-BIH record into a C header the STM32
firmware can replay, plus the golden-reference R-peaks for that exact slice
so you can verify the on-device output matches.

Usage:
    python export_to_c.py 100 --seconds 10      # real record 100, first 10 s
    python export_to_c.py 100 --start 60 --seconds 10
    python export_to_c.py --synthetic           # offline test data, no PhysioNet

Outputs:
    ecg_data.h          -> const double ecg_samples[] + ECG_N/ECG_FS
    expected_rpeaks.txt -> golden-reference R-peak indices for that slice
"""
import sys, argparse
import numpy as np
import golden

FS = 360


def synthetic(seconds):
    rng = np.random.default_rng(7)
    def qrs(width, amp):
        n = int(width * FS); t = np.linspace(-1, 1, n)
        return (amp*np.exp(-(t**2)/0.02) - 0.15*amp*np.exp(-((t+0.25)**2)/0.004)
                - 0.25*amp*np.exp(-((t-0.25)**2)/0.006))
    x = np.zeros(int(seconds*FS)); tf = np.arange(len(x))/FS
    x += 0.05*np.sin(2*np.pi*0.3*tf)
    pos = int(0.5*FS)
    while pos < len(x)-FS:
        rr = int(rng.normal(0.8, 0.05)*FS); w = qrs(0.10, 1.0)
        pos += rr
        if pos+len(w)//2 >= len(x): break
        x[pos-len(w)//2:pos-len(w)//2+len(w)] += w
    x += rng.normal(0, 0.03, len(x))
    return x


def real(record, start, seconds):
    import wfdb
    rec = wfdb.rdrecord(str(record), pn_dir="mitdb")
    sig = rec.p_signal[:, 0].astype(float)
    a = int(start*FS); b = a + int(seconds*FS)
    return sig[a:b]


def write_header(sig, source):
    with open("ecg_data.h", "w") as f:
        f.write("/* auto-generated by export_to_c.py -- do not edit */\n")
        f.write(f"/* source: {source} */\n")
        f.write("#ifndef ECG_DATA_H\n#define ECG_DATA_H\n\n")
        f.write(f"#define ECG_FS {FS}\n")
        f.write(f"#define ECG_N  {len(sig)}\n\n")
        f.write("static const double ecg_samples[ECG_N] = {\n")
        for i in range(0, len(sig), 6):
            row = ", ".join(f"{v:.17g}" for v in sig[i:i+6])
            f.write("  " + row + ",\n")
        f.write("};\n\n#endif\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("record", nargs="?", default=None)
    ap.add_argument("--start", type=float, default=0.0)
    ap.add_argument("--seconds", type=float, default=10.0)
    ap.add_argument("--synthetic", action="store_true")
    args = ap.parse_args()

    if args.synthetic or args.record is None:
        sig = synthetic(args.seconds)
        source = f"synthetic ECG, {args.seconds:.0f}s @ {FS}Hz"
    else:
        sig = real(args.record, args.start, args.seconds)
        source = f"MIT-BIH record {args.record}, {args.start:.0f}-{args.start+args.seconds:.0f}s"

    write_header(sig, source)
    rpeaks, _ = golden.run(sig)
    with open("expected_rpeaks.txt", "w") as f:
        for r in rpeaks:
            f.write(f"{r}\n")

    print(f"wrote ecg_data.h  ({len(sig)} samples, {source})")
    print(f"wrote expected_rpeaks.txt  ({len(rpeaks)} golden R-peaks)")
    print("expected R-peak indices:", rpeaks[:12], "..." if len(rpeaks) > 12 else "")


if __name__ == "__main__":
    main()
