/* biquad.c — Stage 1.4d filter chain (portable C).
 * Coefficients generated by pipeline/noise_filters.py at 360 Hz.
 *
 * Host self-test (proves the C filter matches the Python design):
 *     gcc -DBIQUAD_SELFTEST -O2 biquad.c -o filt_selftest -lm && ./filt_selftest
 */
#include "biquad.h"

/* [0] baseline-wander high-pass 0.5 Hz (Butterworth, 2nd order)
 * [1] mains notch 60 Hz, Q=30                        (both @ 360 Hz) */
static biquad_t sections[2] = {
    { .b0 =  0.99384833f, .b1 = -1.98769666f, .b2 =  0.99384833f,
      .a1 = -1.98765881f, .a2 =  0.98773450f, .z1 = 0.0f, .z2 = 0.0f },
    { .b0 =  0.98284439f, .b1 = -0.98284439f, .b2 =  0.98284439f,
      .a1 = -0.98284439f, .a2 =  0.96568877f, .z1 = 0.0f, .z2 = 0.0f },
};

void ecg_filter_reset(void)
{
    for (int i = 0; i < 2; i++) { sections[i].z1 = 0.0f; sections[i].z2 = 0.0f; }
}

float ecg_filter_sample(float x)
{
    x = biquad_step(&sections[0], x);   /* high-pass */
    x = biquad_step(&sections[1], x);   /* notch     */
    return x;
}

#ifdef BIQUAD_SELFTEST
#include <stdio.h>
#include <math.h>
#define FS 360.0

/* drive a pure tone through the chain and report output/input amplitude in dB,
 * measured after the transient has settled */
static double tone_atten_db(double f_hz, int cycles_settle)
{
    ecg_filter_reset();
    int n_settle = (int)(cycles_settle * FS / f_hz);
    int n_meas   = (int)(4 * FS / f_hz);
    double pk = 0.0;
    for (int n = 0; n < n_settle + n_meas; n++) {
        float x = (float)sin(2.0 * M_PI * f_hz * n / FS);
        float y = ecg_filter_sample(x);
        if (n >= n_settle && fabs(y) > pk) pk = fabs(y);
    }
    return 20.0 * log10(pk / 1.0);   /* input amplitude is 1.0 */
}

int main(void)
{
    printf("Stage 1.4d C filter self-test @ %.0f Hz\n", FS);
    printf("  60 Hz  (mains, should be crushed) : %+6.1f dB\n", tone_atten_db(60.0, 30));
    printf("  0.15 Hz (drift, should be cut)    : %+6.1f dB\n", tone_atten_db(0.15, 4));
    printf("  10 Hz  (QRS band, should pass ~0) : %+6.1f dB\n", tone_atten_db(10.0, 30));
    printf("   1 Hz  (should pass ~0)           : %+6.1f dB\n", tone_atten_db(1.0, 8));
    return 0;
}
#endif
